### ISSUE TITLE
Node not found "$Control/Sprite"

### ISSUE THREAD

**Issue by Mainman002** [thiagobruno/godot_TBP_GrassPath2D#10]
in TBP_GrassLeaf.gd at line 35
```
var sprite = $Control/Sprite
```
node doesn't seem to be found using Godot version 3.2.1-Stable with the Github "Release" you have uploaded currently (didn't download from your master branch yet)

**Comment by thrbr84** [comment]
Thank you, the Github "Release" was really out of date. I uploaded a new version.
